### ISSUE TITLE
[README] Linux install and run instructions

### ISSUE THREAD

**Issue by t04glovern** [t04glovern/maker-today#4]
Include a simple and clean method of installing Hugo on Linux. If an external readme is suited to this in the Hugo docs, add a link to it in the Linux field

https://github.com/t04glovern/maker-today#linux

**Comment by ye-lin-aung** [comment]
Working on it

**Comment by aslafy-z** [comment]
I think the best link to install hugo in any situation is this one: https://gohugo.io/getting-started/installing/

**Comment by t04glovern** [comment]
Assigned to @ye-lin-aung as first, but thank you for posting as well @aslafy-z .

**Comment by 142ayushkumar** [comment]
Can you assign this issue to me?
