### ISSUE TITLE
AWS Deployment Method for Hugo blog

### ISSUE THREAD

**Issue by t04glovern** [t04glovern/maker-today#6]
# Task
I'd like to host this blog on AWS. If anyone has any experience with Hugo site hosting on AWS, and has a nice method of doing so (preferably a method involving **terraform**, **cloud-formation**, or a script with various deployment steps that can be executed from **travis.ci** / **circleCI**

Happy to discuss options here!

**Comment by yamilurbina** [comment]
hi @t04glovern, I'd love to help on this task

This can be achieved with a bucket on AWS s3 and a domain pointing to such bucket: https://alimac.io/static-websites-with-s3-and-hugo-part-1/

Travis can perform the deployment, you'd need to add the `secret` and `access` keys as environment variables. What do you think?
